### PR TITLE
bubble font-face by default and bring it to top level by ignoring wrapped selectors if any

### PR DESCRIPTION
**Pull request by Phanindra48**

### CODE REVIEW

**Comment by Phanindra48** [comment]
`atrule` related code will get invoked only when its added to bubbled list. I was trying to fix an [issue](https://stackoverflow.com/questions/47735847/how-to-access-font-family-defined-in-nested-class/47735954#47735954) we are facing. Please let me know if I missing anything here.

**Comment by ai** [comment]
Yeap, you are right. Nice. I will accept and release it tomorrow.

**Comment by Phanindra48** [comment]
Thank you 👍

**Comment by ai** [comment]
Released in 3.0

**Pull request merged**
