### PR TITLE
fix order of rules

### PR DESCRIPTION
**Pull request by Riim**
Исправление для сломавшегося порядка следования правил.

### CODE REVIEW

**Comment by ai** [comment]
Can you add a test for this fix (I am not sure what order do you try to fix).

**Comment by ai** [comment]
Released in 2.0.1

**Comment by ai** [comment]
Thanks :)

**Comment by skipjack** [comment]
@ai still seeing this issue, can you see my configuration in postcss/postcss-loader#210 to see if anything is off? I can't tell if the issue is this plugin or the loader...

**Comment by ai** [comment]
Can you describe you exactly problem here? Input CSS, output, expected output?

(Today is hard day for me, so I need you help)

**Comment by skipjack** [comment]
Yeah, no worries. I'm actually going to put together a minimal test case for this in the issue I linked to above so I'll cc you once I have that ready.

**Comment by skipjack** [comment]
@ai see the [demo](https://github.com/skipjack/postcss-loader-issue) I just put up.

**Comment by ai** [comment]
Thanks, I will look tomorrow.

**Comment by ai** [comment]
@skipjack I tested with latest `postcss-nested` and output was:

```css
body {
	margin: 0;
}

.test {
	display: flex;
	font-size: 3em;
	height: 100vh;
	justify-content: center;
	align-items: center;
	color: black;
	background: grey;
}

.test--white {
		color: white;
	}

.test--blue {
		color: blue;
	}
```

Very strange that we have different behaviour in your demo.

**Comment by skipjack** [comment]
Ah thanks for testing... it actually turned out to be postcss-cssnext, sorry for bugging you!

**Pull request merged**
