### PR TITLE
adding font-face at-rule to default bubbling rules

### PR DESCRIPTION
**Pull request by komlev**
@font-face gets wrapped

### CODE REVIEW

**Comment by ai** [comment]
Hm. But bubbling will move selector from top to bottom level.

```css
.phone {
    @media (max-width: 500px) {
        width: auto;
    }
}
```

```css
@media (max-width: 500px) {
    .phone {
        width: auto;
    }
}
```

How it will works with `@font-face`?

**Comment by komlev** [comment]
Ah, yes, I see the problem. I guess wrapping needs to ingore font-face at all.

**Comment by ai** [comment]
We can add special option for at-rules that should be bubble without any selector changes.

**Comment by Phanindra48** [comment]
Hi ai, I have created a PR for this issue https://github.com/postcss/postcss-nested/pull/69.

**Comment by ai** [comment]
Released in 3.0

**Pull request merged**
