### PR TITLE
generate correct styles when &, nest, adjacent

### PR DESCRIPTION
**Pull request by marzk**
``` scss
.parent {
  .adjacent {
    &-left+&-right {
      background-color: black;
    }
  }
  .adjacent-left+.adjacent-right {
    background-color: black;
  }
}
```

compile

``` css
/* Error, it will never work */
.parent .adjacent-left + .parent .adjacent-right {
  background-color: black;
}
/* Correct */
.parent .adjacent-left + .adjacent-right {
  background-color: black;
}
```

fix this bug. [error demo](https://jsfiddle.net/ms6q4rqj/1/)

### CODE REVIEW

**Comment by ai** [comment]
Yeap, it is a bug. But can we make fix more clear?

Can you explain, what this code does:

```js
result.push(j.replace('&', i)
  .replace(/&/g, postcss.list.space(i).pop())
);
```

**Comment by marzk** [comment]
it just replace the first '&' with i, others '&' should be replace the i(last selector)
eg.
i may be '.parent .abjacent', so the first '&' should be replace by it. But others should be replace by the '.abjacent'.

**Comment by ai** [comment]
@marzk hm, this way is for `+` only, but you didn’t keep it for `+` only in the code. What will be on `&:hover,&:focus`?

**Comment by marzk** [comment]
sorry for my not fully considered. It has the problem in my pr.

**Comment by ai** [comment]
I am waiting for fix :)

**Comment by marzk** [comment]
im thinking about it again. `&:hover,&:focus` will be parsed to two selector `&:hover` and `&:focus`, so it will be ok.

im considering other [combinators](https://developer.mozilla.org/en-US/docs/Glossary/CSS_Selector).

**Comment by ai** [comment]
At least `&&` will works differ.

Right now `&` works simple and expected. This fix add unexpected behavior.

**Comment by ai** [comment]
Noone support it, closing. It is OK to create a separated plugin with `&&` support.

**Pull request closed without merging**
